// Code generated by protoc-gen-go. DO NOT EDIT.
// source: getArea.proto

package go_micro_srv_getArea

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_420050f84ccd68e8, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Errno                string         `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string         `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 []*GatAreainfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_420050f84ccd68e8, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() []*GatAreainfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GatAreainfo struct {
	Aid                  string   `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Aname                string   `protobuf:"bytes,2,opt,name=aname,proto3" json:"aname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatAreainfo) Reset()         { *m = GatAreainfo{} }
func (m *GatAreainfo) String() string { return proto.CompactTextString(m) }
func (*GatAreainfo) ProtoMessage()    {}
func (*GatAreainfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_420050f84ccd68e8, []int{2}
}

func (m *GatAreainfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatAreainfo.Unmarshal(m, b)
}
func (m *GatAreainfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatAreainfo.Marshal(b, m, deterministic)
}
func (m *GatAreainfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatAreainfo.Merge(m, src)
}
func (m *GatAreainfo) XXX_Size() int {
	return xxx_messageInfo_GatAreainfo.Size(m)
}
func (m *GatAreainfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GatAreainfo.DiscardUnknown(m)
}

var xxx_messageInfo_GatAreainfo proto.InternalMessageInfo

func (m *GatAreainfo) GetAid() string {
	if m != nil {
		return m.Aid
	}
	return ""
}

func (m *GatAreainfo) GetAname() string {
	if m != nil {
		return m.Aname
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.getArea.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.getArea.Response")
	proto.RegisterType((*GatAreainfo)(nil), "go.micro.srv.getArea.GatAreainfo")
}

func init() { proto.RegisterFile("getArea.proto", fileDescriptor_420050f84ccd68e8) }

var fileDescriptor_420050f84ccd68e8 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4f, 0xc4, 0x30,
	0x0c, 0x85, 0x39, 0x7a, 0xdc, 0x81, 0x0f, 0x24, 0x64, 0x9d, 0x50, 0x85, 0x74, 0xa8, 0x64, 0xea,
	0x94, 0xa1, 0xa8, 0x3f, 0x80, 0xa9, 0x13, 0x42, 0xca, 0xc8, 0x16, 0xa8, 0xa9, 0x3a, 0x34, 0x2e,
	0x4e, 0xe0, 0xf7, 0xa3, 0x26, 0x19, 0x18, 0xca, 0x14, 0x3f, 0xdb, 0xca, 0xf7, 0x9e, 0xe1, 0x66,
	0xa0, 0xf0, 0x2c, 0x64, 0xf5, 0x2c, 0x1c, 0x18, 0x8f, 0x03, 0xeb, 0x69, 0xfc, 0x10, 0xd6, 0x5e,
	0x7e, 0x74, 0x9e, 0xa9, 0x13, 0xec, 0x0d, 0x7d, 0x7d, 0x93, 0x0f, 0x88, 0xb0, 0x75, 0x76, 0xa2,
	0x72, 0x53, 0x6d, 0xea, 0x2b, 0x13, 0x6b, 0xc5, 0x70, 0x69, 0xc8, 0xcf, 0xec, 0x3c, 0xe1, 0x11,
	0x2e, 0x48, 0xc4, 0x71, 0x5e, 0x48, 0x02, 0xef, 0x60, 0x47, 0x22, 0x93, 0x1f, 0xca, 0xf3, 0xd8,
	0xce, 0x0a, 0x5b, 0xd8, 0xf6, 0x36, 0xd8, 0xb2, 0xa8, 0x8a, 0xfa, 0xd0, 0x3c, 0xea, 0x35, 0xba,
	0xee, 0x6c, 0x7c, 0x47, 0xf7, 0xc9, 0x26, 0xae, 0xab, 0x16, 0x0e, 0x7f, 0x9a, 0x78, 0x0b, 0x85,
	0x1d, 0xfb, 0x4c, 0x5c, 0xca, 0xc5, 0x85, 0x8d, 0x36, 0x13, 0x2e, 0x89, 0xe6, 0x0d, 0xf6, 0x5d,
	0xfa, 0x13, 0x5f, 0xe1, 0xfa, 0x65, 0x01, 0x65, 0x06, 0x9e, 0xd6, 0xd1, 0x39, 0xf5, 0xfd, 0xc3,
	0x7f, 0xe3, 0x94, 0x5a, 0x9d, 0xbd, 0xef, 0xe2, 0xfd, 0x9e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xc2, 0x48, 0xb6, 0x9c, 0x50, 0x01, 0x00, 0x00,
}
