// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/register/register.proto

package go_micro_srv_register

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Request) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type Regrequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SmsCode              string   `protobuf:"bytes,3,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Regrequest) Reset()         { *m = Regrequest{} }
func (m *Regrequest) String() string { return proto.CompactTextString(m) }
func (*Regrequest) ProtoMessage()    {}
func (*Regrequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{2}
}

func (m *Regrequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Regrequest.Unmarshal(m, b)
}
func (m *Regrequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Regrequest.Marshal(b, m, deterministic)
}
func (m *Regrequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Regrequest.Merge(m, src)
}
func (m *Regrequest) XXX_Size() int {
	return xxx_messageInfo_Regrequest.Size(m)
}
func (m *Regrequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Regrequest.DiscardUnknown(m)
}

var xxx_messageInfo_Regrequest proto.InternalMessageInfo

func (m *Regrequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Regrequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Regrequest) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

type Regresponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Regresponse) Reset()         { *m = Regresponse{} }
func (m *Regresponse) String() string { return proto.CompactTextString(m) }
func (*Regresponse) ProtoMessage()    {}
func (*Regresponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{3}
}

func (m *Regresponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Regresponse.Unmarshal(m, b)
}
func (m *Regresponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Regresponse.Marshal(b, m, deterministic)
}
func (m *Regresponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Regresponse.Merge(m, src)
}
func (m *Regresponse) XXX_Size() int {
	return xxx_messageInfo_Regresponse.Size(m)
}
func (m *Regresponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Regresponse.DiscardUnknown(m)
}

var xxx_messageInfo_Regresponse proto.InternalMessageInfo

func (m *Regresponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Regresponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type LoginRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRegresponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRegresponse) Reset()         { *m = LoginRegresponse{} }
func (m *LoginRegresponse) String() string { return proto.CompactTextString(m) }
func (*LoginRegresponse) ProtoMessage()    {}
func (*LoginRegresponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{5}
}

func (m *LoginRegresponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRegresponse.Unmarshal(m, b)
}
func (m *LoginRegresponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRegresponse.Marshal(b, m, deterministic)
}
func (m *LoginRegresponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRegresponse.Merge(m, src)
}
func (m *LoginRegresponse) XXX_Size() int {
	return xxx_messageInfo_LoginRegresponse.Size(m)
}
func (m *LoginRegresponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRegresponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRegresponse proto.InternalMessageInfo

func (m *LoginRegresponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *LoginRegresponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *LoginRegresponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.register.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.register.Response")
	proto.RegisterType((*Regrequest)(nil), "go.micro.srv.register.Regrequest")
	proto.RegisterType((*Regresponse)(nil), "go.micro.srv.register.Regresponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.register.LoginRequest")
	proto.RegisterType((*LoginRegresponse)(nil), "go.micro.srv.register.LoginRegresponse")
}

func init() { proto.RegisterFile("proto/register/register.proto", fileDescriptor_164fcd282674ab7a) }

var fileDescriptor_164fcd282674ab7a = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3f, 0x4f, 0xf3, 0x40,
	0x0c, 0xc6, 0xdf, 0xf6, 0x85, 0xb6, 0x31, 0x0c, 0xe8, 0x04, 0x28, 0x44, 0xe2, 0xdf, 0x31, 0xc0,
	0x74, 0x48, 0xb0, 0x20, 0xb1, 0xc1, 0x84, 0xd4, 0x01, 0x85, 0x6e, 0x1d, 0x50, 0xdb, 0x58, 0x51,
	0x24, 0x2e, 0x0e, 0xe7, 0x0b, 0xf0, 0x1d, 0xf8, 0xd2, 0x28, 0x97, 0x4b, 0xd4, 0x81, 0x14, 0x29,
	0x9b, 0xed, 0xb3, 0x7f, 0x79, 0xfc, 0x38, 0x70, 0x5c, 0x18, 0xb2, 0x74, 0x6d, 0x30, 0xcd, 0xd8,
	0xa2, 0x69, 0x03, 0xe5, 0xea, 0xe2, 0x20, 0x25, 0xa5, 0xb3, 0x95, 0x21, 0xc5, 0xe6, 0x43, 0x35,
	0x8f, 0xf2, 0x09, 0xc6, 0x31, 0xbe, 0x97, 0xc8, 0x56, 0x1c, 0xc2, 0x48, 0xd3, 0x32, 0x7b, 0xc3,
	0x70, 0x70, 0x36, 0xb8, 0x0a, 0x62, 0x9f, 0x09, 0x01, 0x5b, 0x16, 0xbf, 0x6c, 0x38, 0x74, 0x55,
	0x17, 0x57, 0xb5, 0xb2, 0xcc, 0x92, 0xf0, 0x7f, 0x5d, 0xab, 0x62, 0x79, 0x07, 0x93, 0x18, 0xb9,
	0xa0, 0x9c, 0x51, 0xec, 0xc3, 0x36, 0x1a, 0x93, 0x93, 0x47, 0xd5, 0x49, 0xf5, 0x05, 0x34, 0x46,
	0x73, 0xea, 0x59, 0x3e, 0x93, 0x73, 0x80, 0x18, 0x53, 0xf3, 0x87, 0x8e, 0x08, 0x26, 0xc5, 0x82,
	0xf9, 0x93, 0x4c, 0xe2, 0xe7, 0xdb, 0x5c, 0x1c, 0xc1, 0x84, 0x35, 0xbf, 0xae, 0x28, 0x41, 0xaf,
	0x69, 0xcc, 0x9a, 0x1f, 0x29, 0x41, 0x79, 0x0f, 0x3b, 0x0e, 0xde, 0x4b, 0xd9, 0x03, 0xec, 0x4e,
	0x29, 0xcd, 0xf2, 0xb8, 0xbf, 0x36, 0x39, 0x83, 0x3d, 0xcf, 0xe8, 0xa9, 0xa2, 0x72, 0x3b, 0x5f,
	0xe8, 0x66, 0x33, 0x17, 0xdf, 0x7c, 0x0f, 0x2b, 0xbb, 0xeb, 0x2b, 0x8a, 0x29, 0x8c, 0x5f, 0xea,
	0x75, 0xc5, 0x89, 0xfa, 0xf5, 0xd0, 0xca, 0x6f, 0x10, 0x9d, 0x76, 0xbe, 0xd7, 0xd2, 0xe4, 0x3f,
	0x31, 0x83, 0xc0, 0x91, 0x1d, 0xef, 0xbc, 0xb3, 0xbf, 0x39, 0x58, 0x24, 0x37, 0xb5, 0xb4, 0xd4,
	0x39, 0x04, 0xce, 0x86, 0x67, 0x62, 0x2b, 0x2e, 0x3a, 0x46, 0xd6, 0xcd, 0x8e, 0x2e, 0x37, 0x37,
	0xad, 0xc1, 0x97, 0x23, 0xf7, 0x93, 0xdf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x97, 0x8d, 0x2b,
	0xa9, 0x05, 0x03, 0x00, 0x00,
}
