// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdataUserRequest struct {
	Oldname              string   `protobuf:"bytes,1,opt,name=oldname,proto3" json:"oldname,omitempty"`
	Xinname              string   `protobuf:"bytes,2,opt,name=xinname,proto3" json:"xinname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdataUserRequest) Reset()         { *m = UpdataUserRequest{} }
func (m *UpdataUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdataUserRequest) ProtoMessage()    {}
func (*UpdataUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *UpdataUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdataUserRequest.Unmarshal(m, b)
}
func (m *UpdataUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdataUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdataUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdataUserRequest.Merge(m, src)
}
func (m *UpdataUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdataUserRequest.Size(m)
}
func (m *UpdataUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdataUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdataUserRequest proto.InternalMessageInfo

func (m *UpdataUserRequest) GetOldname() string {
	if m != nil {
		return m.Oldname
	}
	return ""
}

func (m *UpdataUserRequest) GetXinname() string {
	if m != nil {
		return m.Xinname
	}
	return ""
}

type UpdataUserResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 *Updata  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdataUserResponse) Reset()         { *m = UpdataUserResponse{} }
func (m *UpdataUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdataUserResponse) ProtoMessage()    {}
func (*UpdataUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *UpdataUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdataUserResponse.Unmarshal(m, b)
}
func (m *UpdataUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdataUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdataUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdataUserResponse.Merge(m, src)
}
func (m *UpdataUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdataUserResponse.Size(m)
}
func (m *UpdataUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdataUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdataUserResponse proto.InternalMessageInfo

func (m *UpdataUserResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *UpdataUserResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *UpdataUserResponse) GetData() *Updata {
	if m != nil {
		return m.Data
	}
	return nil
}

type Updata struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Updata) Reset()         { *m = Updata{} }
func (m *Updata) String() string { return proto.CompactTextString(m) }
func (*Updata) ProtoMessage()    {}
func (*Updata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Updata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Updata.Unmarshal(m, b)
}
func (m *Updata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Updata.Marshal(b, m, deterministic)
}
func (m *Updata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Updata.Merge(m, src)
}
func (m *Updata) XXX_Size() int {
	return xxx_messageInfo_Updata.Size(m)
}
func (m *Updata) XXX_DiscardUnknown() {
	xxx_messageInfo_Updata.DiscardUnknown(m)
}

var xxx_messageInfo_Updata proto.InternalMessageInfo

func (m *Updata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Errno                string    `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string    `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 *Userdata `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() *Userdata {
	if m != nil {
		return m.Data
	}
	return nil
}

type Userdata struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	RealName             string   `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCard               string   `protobuf:"bytes,5,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Userdata) Reset()         { *m = Userdata{} }
func (m *Userdata) String() string { return proto.CompactTextString(m) }
func (*Userdata) ProtoMessage()    {}
func (*Userdata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *Userdata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Userdata.Unmarshal(m, b)
}
func (m *Userdata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Userdata.Marshal(b, m, deterministic)
}
func (m *Userdata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Userdata.Merge(m, src)
}
func (m *Userdata) XXX_Size() int {
	return xxx_messageInfo_Userdata.Size(m)
}
func (m *Userdata) XXX_DiscardUnknown() {
	xxx_messageInfo_Userdata.DiscardUnknown(m)
}

var xxx_messageInfo_Userdata proto.InternalMessageInfo

func (m *Userdata) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Userdata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Userdata) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Userdata) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Userdata) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *Userdata) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdataUserRequest)(nil), "go.micro.srv.user.UpdataUserRequest")
	proto.RegisterType((*UpdataUserResponse)(nil), "go.micro.srv.user.UpdataUserResponse")
	proto.RegisterType((*Updata)(nil), "go.micro.srv.user.Updata")
	proto.RegisterType((*Request)(nil), "go.micro.srv.user.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user.Response")
	proto.RegisterType((*Userdata)(nil), "go.micro.srv.user.Userdata")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x6f, 0x7a, 0xd3, 0xa4, 0x39, 0x77, 0xd5, 0xc3, 0xbd, 0xb7, 0xb1, 0xb5, 0x50, 0x82,
	0x42, 0x37, 0xa6, 0x50, 0x1f, 0x41, 0x50, 0x5c, 0xe8, 0x22, 0xd0, 0x95, 0x8b, 0x30, 0xed, 0x0c,
	0x25, 0x90, 0x64, 0xda, 0x33, 0x69, 0xf1, 0x81, 0xdc, 0xf9, 0x92, 0x32, 0x33, 0x89, 0x8d, 0x18,
	0x11, 0xdc, 0x94, 0x7e, 0xe7, 0x3b, 0x7f, 0x7e, 0x67, 0x72, 0xe0, 0xdf, 0x8e, 0x64, 0x25, 0x17,
	0x07, 0x25, 0xc8, 0xfc, 0xc4, 0x46, 0xe3, 0x70, 0x2b, 0xe3, 0x22, 0xdb, 0x90, 0x8c, 0x15, 0x1d,
	0x63, 0x6d, 0x44, 0x77, 0x30, 0x5c, 0xed, 0x38, 0xab, 0xd8, 0x4a, 0x09, 0x4a, 0xc4, 0xfe, 0x20,
	0x54, 0x85, 0x21, 0xf8, 0x32, 0xe7, 0x25, 0x2b, 0x44, 0xe8, 0xcc, 0x9c, 0x79, 0x90, 0x34, 0x52,
	0x3b, 0xcf, 0x59, 0x69, 0x9c, 0x9e, 0x75, 0x6a, 0x19, 0xed, 0x01, 0xdb, 0x8d, 0xd4, 0x4e, 0x96,
	0x4a, 0xe0, 0x5f, 0xe8, 0x0b, 0xa2, 0x52, 0xd6, 0x7d, 0xac, 0xc0, 0xff, 0xe0, 0x09, 0xa2, 0x42,
	0x6d, 0xeb, 0x26, 0xb5, 0xc2, 0x2b, 0x70, 0x75, 0x87, 0xf0, 0xf7, 0xcc, 0x99, 0xff, 0x59, 0x9e,
	0xc5, 0x9f, 0x70, 0x63, 0x3b, 0x22, 0x31, 0x69, 0xd1, 0x39, 0x78, 0x56, 0x23, 0x82, 0xdb, 0xa2,
	0x35, 0xff, 0xa3, 0x29, 0xf8, 0xcd, 0x3e, 0x5d, 0x76, 0x06, 0x83, 0x1f, 0x52, 0x2e, 0x3e, 0x50,
	0x4e, 0xba, 0x28, 0x95, 0xa0, 0x16, 0xe7, 0x8b, 0x03, 0x83, 0x26, 0x84, 0x23, 0xf0, 0x75, 0x4e,
	0x9a, 0x71, 0x33, 0xad, 0x9f, 0x78, 0x5a, 0xde, 0xf3, 0x77, 0xc8, 0xde, 0x09, 0x52, 0x23, 0x14,
	0x72, 0x9d, 0xe5, 0xc2, 0x0c, 0x0b, 0x92, 0x5a, 0xe1, 0x04, 0x02, 0x12, 0x2c, 0x4f, 0x4d, 0x81,
	0x6b, 0xac, 0x81, 0x0e, 0x3c, 0xea, 0xa2, 0x11, 0xf8, 0x19, 0x4f, 0x37, 0x8c, 0x78, 0xd8, 0xb7,
	0x55, 0x19, 0xbf, 0x61, 0xc4, 0x71, 0x0a, 0xc0, 0x8e, 0xac, 0x62, 0x94, 0x1e, 0x28, 0x0f, 0x3d,
	0xe3, 0x05, 0x36, 0xb2, 0xa2, 0x7c, 0xf9, 0xea, 0x80, 0xab, 0x31, 0xf1, 0x16, 0x82, 0x07, 0xbd,
	0x90, 0x11, 0xe3, 0x8e, 0xfd, 0xea, 0x77, 0x1d, 0x4f, 0x3a, 0x3d, 0xfb, 0xa8, 0xd1, 0x2f, 0x7c,
	0x02, 0x38, 0x9d, 0x04, 0x5e, 0x7c, 0xf9, 0x39, 0x5b, 0xa7, 0x37, 0xbe, 0xfc, 0x26, 0xab, 0x69,
	0xbe, 0xf6, 0xcc, 0x49, 0x5f, 0xbf, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x12, 0xec, 0x31, 0xeb,
	0x02, 0x00, 0x00,
}
